name: recaptcha
version: 0.0.1
author: Sergey Akopkokhyants <akserg@google.com>
description: ReCaptcha is a server side Dart library for interfacing with ReCaptcha service
homepage: https://github.com/akserg/recaptcha
dependencies:
  http: '>=0.11.1+1 <0.12.0'
dev_dependencies:
  unittest: '>=0.11.0+4 <0.12.0'
